### ISSUE TITLE
cx_Freeze error when application is launched

### ISSUE THREAD

**Issue by skmezanul** [niyazialpay/CloudFlareDNSManager#8]
After launching the application for the first time, I tried to save the API key and email address, but the application crashed.

Upon relaunching, it is showing cx_Freeze error window.

I tested it on Windows 10 Pro (x64).

![CloudFlareDNSManager_5TMnGsnx84](https://user-images.githubusercontent.com/2069097/229207363-2668c069-4b8b-4d81-a686-e10853180aa2.png)

P.S. I don't have that user on my Windows system which the error is referring to.

**Comment by niyazialpay** [comment]
You probably entered your API information incorrectly. After deleting the lib/DB/system.db file, you can restart the application.
